name: Maven Build (mvn verify)

on:
  workflow_call:
    inputs:
      jdkVersion:
        type: string
        description: "Version of the JDK to setup and use"
        required: false
        default: "17"

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK ${{ inputs.jdkVersion }}
      uses: actions/setup-java@v3
      with:
        java-version: ${{ inputs.jdkVersion }}
        distribution: temurin
        cache: maven
    - name: Build with Maven
      run: mvn -B verify --file pom.xml
